In [1]:
import torch
import jieba
import random

import numpy as np

from data import Data
from torch import nn, optim
from datetime import datetime
from torch.utils.data import DataLoader, Dataset

c:\Users\User\anaconda3\envs\pytorch\lib\site-packages\tqdm\auto.py:21: TqdmWarning: IProgress not found. Please update jupyter and ipywidgets. See https://ipywidgets.readthedocs.io/en/stable/user_install.html
  from .autonotebook import tqdm as notebook_tqdm


In [2]:
# Set random seed.
random_seed = 0

random.seed(random_seed)
np.random.seed(random_seed)
torch.manual_seed(random_seed)
torch.cuda.manual_seed(random_seed)
torch.backends.cudnn.benchmark = False
torch.backends.cudnn.deterministic = True

In [3]:
device = "cpu"

if torch.cuda.is_available():
    device = "cuda:0"

print(device)

cuda:0


In [4]:
classes = {
    0: "牡羊",
    1: "金牛",
    2: "雙子",
    3: "巨蠍",
    4: "獅子",
    5: "處女",
    6: "天秤",
    7: "天蠍",
    8: "射手",
    9: "魔羯",
    10: "水瓶",
    11: "雙魚",
}

In [5]:
raw = {i: open(f"./dataset/{classes[i]}.txt", encoding="utf-8").read() for i in range(12)}
data = Data(data=raw, padding_length=32)

train_raw = data.get("data")

Building prefix dict from the default dictionary ...
Loading model from cache C:\Users\User\AppData\Local\Temp\jieba.cache


Cleaning completed.
ToDataset completed.
Argumantation completed.


Loading model cost 0.523 seconds.
Prefix dict has been built successfully.


Tokenlization completed.
Padding completed.
Token2id completed.
Process completed.


In [6]:
len(train_raw)

6327

In [7]:
train_raw[0]

[[3369,
  2899,
  3515,
  3828,
  3959,
  2455,
  2775,
  1360,
  4646,
  2219,
  1428,
  1428,
  1428,
  1428,
  1428,
  1428,
  1428,
  1428,
  1428,
  1428,
  1428,
  1428,
  1428,
  1428,
  1428,
  1428,
  1428,
  1428,
  1428,
  1428,
  1428,
  1428],
 [1, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0]]

In [8]:
class CreateDataset(Dataset):
    def __init__(self, data: list, label: list):
        self.data = data
        self.label = label

    def __getitem__(self, index):
        return torch.tensor(self.data[index]), torch.tensor(self.label[index], dtype=torch.float)

    def __len__(self):
        return len(self.label)

In [9]:
d, l = [], []

for i, j in train_raw:
    d.append(i); l.append(j)

train_ds = CreateDataset(d, l)

In [10]:
train_ds[1]

(tensor([3369, 2899, 3515, 3828, 3959, 2455, 2775, 1360, 4646, 2219, 1428, 1428,
         1428, 1428, 1428, 1428, 1428, 1428, 1428, 1428, 1428, 1428, 1428, 1428,
         1428, 1428, 1428, 1428, 1428, 1428, 1428, 1428]),
 tensor([1., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0.]))

In [11]:
train_dl = DataLoader(train_ds, batch_size=8, shuffle=True)

In [12]:
class Attention(nn.Module):
    def __init__(self):
        super(Attention, self).__init__()
        self.linear1 = nn.Linear(256, 24)
        self.linear2 = nn.Linear(24, 1)
        self.relu = nn.ReLU(True)

    def forward(self, x: torch.Tensor):
        b = x.size(0)
        x = x.reshape(-1, 256)

        x = self.linear1(x)
        x = self.relu(x)
        x = self.linear2(x)

        x = x.reshape(b, -1)
        x = torch.softmax(x, dim=1)

        return x.unsqueeze(2)

In [13]:
class AttentionClassifier(nn.Module):
    def __init__(self):
        super(AttentionClassifier, self).__init__()
        self.attention = Attention()
        self.linear = nn.Linear(256, 12)

    def forward(self, x: torch.Tensor):
        attention = self.attention(x)

        x = (x * attention).sum(dim=1)
        x = torch.log_softmax(self.linear(x), dim=1)

        return x, attention

In [14]:
class Model(nn.Module):
    def __init__(self) -> None:
        super(Model, self).__init__()
        self.embedding = nn.Embedding(data.get("token_len"), 64)
        self.lstm = nn.LSTM(
            input_size=64,
            hidden_size=256,
            num_layers=4,
            dropout=0.5,
            batch_first=True,
            bidirectional=True
        )
        self.linear = nn.Linear(16384, 12)
        self.classifier = AttentionClassifier()

    def forward(self, x: torch.Tensor):
        x = self.embedding(x)
        x, _ = self.lstm(x)

        x = x[:, :, :256] + x[:, :, :256]

        x, _ = self.classifier(x)

        return x

In [15]:
model = Model().to(device=device)

In [16]:
epochs = 30
optimizer = optim.SGD(model.parameters(), lr=0.1)
loss = nn.CrossEntropyLoss()

In [17]:
# Traning history data.
train_accuracy_h = []
train_loss_h = []
validate_accuracy_h = []

In [18]:
def train(epochs: int, model: nn.Module, optimizer: optim.Optimizer, loss: nn.CrossEntropyLoss, dataloader: DataLoader):
    # Set model to training mode.
    model.train()

    for epoch in range(epochs):

        train_accuracy = 0
        train_loss = 0
        train_total = 0
        train_process = 0
        train_time = datetime.now().timestamp()

        for texts, labels in dataloader:
            texts: torch.Tensor
            labels: torch.Tensor

            texts = texts.to(device)
            labels = labels.to(device)

            outputs: torch.Tensor = model(texts)
            losses: torch.Tensor = loss(outputs, labels)

            # optimizer.zero_grad()
            for param in model.parameters(): param.grad = None

            # Backpropagation.
            losses.backward()

            # Update parameters.
            optimizer.step()

            _, predict = torch.max(outputs, 1)
            train_accuracy += sum([labels[i][predict[i]] == 1 for i in range(len(predict))])
            train_loss += losses.item()
            train_total += labels.shape[0]
            train_process += 1

            print(
                f"{datetime.now().strftime('%Y/%m/%d %H:%M:%S')} "
                f"Epoch: {epoch:03d} "
                f"Time: {datetime.now().timestamp() - train_time:.2f} "
                f"Process: {train_process / len(dataloader) * 100:.2f}% "
                f"Accuracy: {train_accuracy / train_total * 100:.2f}% "
                f"Loss: {train_loss:.3f}",
                end="\r"
            )

        train_accuracy_h.append(train_accuracy / train_total * 100)
        train_loss_h.append(train_loss)

        print()

        # Early stop.
        if train_accuracy / train_total > 0.99:
            print("Early stopped.")
            break

    # Set model to evaluation mode.
    model.eval()

In [19]:
train(epochs=epochs, model=model, optimizer=optimizer, loss=loss, dataloader=train_dl)

2024/04/01 17:19:37 Epoch: 000 Time: 15.22 Process: 100.00% Accuracy: 10.34% Loss: 1964.608
2024/04/01 17:19:51 Epoch: 001 Time: 13.76 Process: 100.00% Accuracy: 11.16% Loss: 1960.328
2024/04/01 17:20:04 Epoch: 002 Time: 13.60 Process: 100.00% Accuracy: 12.23% Loss: 1955.031
2024/04/01 17:20:18 Epoch: 003 Time: 13.94 Process: 100.00% Accuracy: 13.99% Loss: 1939.723
2024/04/01 17:20:33 Epoch: 004 Time: 14.11 Process: 100.00% Accuracy: 17.10% Loss: 1848.588
2024/04/01 17:20:47 Epoch: 005 Time: 14.19 Process: 100.00% Accuracy: 24.15% Loss: 1709.146
2024/04/01 17:21:01 Epoch: 006 Time: 14.36 Process: 100.00% Accuracy: 30.66% Loss: 1569.472
2024/04/01 17:21:15 Epoch: 007 Time: 14.38 Process: 100.00% Accuracy: 36.98% Loss: 1432.271
2024/04/01 17:21:30 Epoch: 008 Time: 14.41 Process: 100.00% Accuracy: 43.76% Loss: 1271.954
2024/04/01 17:21:44 Epoch: 009 Time: 14.42 Process: 100.00% Accuracy: 52.17% Loss: 1086.149
2024/04/01 17:21:59 Epoch: 010 Time: 14.47 Process: 100.00% Accuracy: 62.76% Los

In [20]:
for i, j in train_dl:
    print(i)
    print(model(i.to(device)))
    print(j)
    break

tensor([[3453,  416, 3257, 3361, 4929, 1901, 4147, 5283, 1389,  168, 4378, 4929,
         2822, 3546, 2219, 1428, 1428, 1428, 1428, 1428, 1428, 1428, 1428, 1428,
         1428, 1428, 1428, 1428, 1428, 1428, 1428, 1428],
        [4775, 5127, 1004, 1360, 2256, 2219, 3959, 2411, 1719, 1395,  323, 3353,
         5407,  323, 3353, 5283,  379, 3369, 1201,  376, 3104, 2611, 1815, 3820,
         1360, 1279, 5283, 2654,  182, 4633, 3632, 3301],
        [5321, 1321, 4537, 2011, 1033, 1360, 5283,  176, 4929, 1321, 2245, 5283,
         2813, 1251, 5283, 1863, 1321, 5193, 2379,  740, 2219, 1428, 1428, 1428,
         1428, 1428, 1428, 1428, 1428, 1428, 1428, 1428],
        [3652, 1834, 5198, 5193, 2825, 3960, 5041, 4929, 3786, 1360,  427, 5283,
          568, 5283, 5321, 1719,  570, 1360, 2551, 2344, 4929, 4112, 1067, 1000,
         1798,  355, 2219, 1428, 1428, 1428, 1428, 1428],
        [1834, 4227, 1120, 1360, 4509, 3429, 5097, 2602, 2219, 1428, 1428, 1428,
         1428, 1428, 1428, 1428, 1428, 

In [21]:
testset = [
    "勇敢無畏，充滿了活力和冒險精神，他們喜歡追求挑戰，敢於冒險，常常是行動派的領導者。",
    "穩重可靠，以堅韌的意志力和耐心著稱，他們注重安全和舒適，並對物質生活有著強烈的執著。",
    "機智聰明，好奇心旺盛，喜歡交際和表達自己，具有多才多藝的特質，常常充滿了靈活的思維和活力。",
    "情感豐富，善解人意，對家庭和親密關係非常重視，他們總是充滿了溫柔和關懷，是很好的傾聽者和支持者。",
    "自信大方，追求著成為焦點的慾望，他們充滿了熱情和活力，喜歡引領和影響身邊的人，時常展現出優越感和領導能力。",
    "細心謹慎，追求完美，他們善於分析和解決問題，注重細節和有組織性，常常是值得信賴的夥伴和顧問。",
    "追求和諧，優雅而公正，他們注重平衡和公平，善於溝通協調，是很好的調解者和中介者。",
    "神秘內斂，充滿了熱情和直覺，他們擁有強烈的意志力和洞察力，常常是充滿挑戰性和魅力的個體。",
    "自由奔放，熱愛冒險和探索，他們追求著廣闊的視野和新鮮的體驗，時常充滿了樂觀和幽默。",
    "勤奮負責，追求事業成功和社會地位，他們具有堅毅的意志力和耐心，常常是穩健和實際的決策者。",
    "獨立思考，充滿了理想主義和創意，他們追求著獨特的生活方式和社會價值觀，常常是前衛和不拘一格的個體。",
    "敏感善良，充滿了同情心和想像力，他們常常是理想主義者和夢想家，追求著內心的情感和精神實踐。",
    "勇敢無畏，充滿活力，喜歡追求挑戰，常常是行動派的領導者。",
    "穩重可靠，堅韌耐心，注重安全舒適，對物質生活有強烈執著。",
    "機智聰明，好奇心旺盛，善於交際表達，充滿靈活思維和活力。",
    "情感豐富，善解人意，重視家庭和親密關係，溫柔關懷，傾聽支持者。",
    "自信大方，追求成為焦點，充滿熱情活力，喜歡引領影響身邊的人。",
    "細心謹慎，追求完美，善於分析解決問題，注重細節有組織性。",
    "追求和諧，優雅公正，注重平衡公平，善於溝通協調。",
    "神秘內斂，熱情直覺，意志力洞察力強，充滿挑戰性和魅力。",
    "自由奔放，熱愛冒險探索，追求廣闊視野和新鮮體驗，樂觀幽默。",
    "勤奮負責，追求事業成功社會地位，具堅毅意志力和耐心，穩健決策者。",
    "獨立思考，理想主義創意，追求獨特生活方式和價值觀，前衛不拘一格。",
    "敏感善良，同情心想像力豐富，理想主義夢想家，追求內心情感精神實踐。",
    "勇敢果敢，充滿活力，愛冒險。",
    "穩重堅定，堅持自我價值觀。",
    "靈活機智，善於溝通交際。",
    "情感豐富，家庭意識強。",
    "自信領導，熱情奔放。",
    "細心謹慎，追求完美。",
    "追求和諧，公正公平。",
    "神秘敏感，探索深度。",
    "自由探險，樂觀向上。",
    "勤奮穩健，追求成功。",
    "獨立創新，理想主義者。",
    "敏感浪漫，夢想家。",
]

answare = [
    '牡羊', '金牛', '雙子', '巨蠍', '獅子', '處女', '天秤', '天蠍', '射手', '魔羯', '水瓶', '雙魚',
    '牡羊', '金牛', '雙子', '巨蠍', '獅子', '處女', '天秤', '天蠍', '射手', '魔羯', '水瓶', '雙魚',
    '牡羊', '金牛', '雙子', '巨蠍', '獅子', '處女', '天秤', '天蠍', '射手', '魔羯', '水瓶', '雙魚',
]

In [22]:
def process(testset: list) -> torch.Tensor:
    result = []

    for line in testset:
        temp = jieba.lcut(line)
        temp = temp + ["<PAD>"] * (32 - len(temp))
        temp = [data.w2i[x] if x in data.w2i else data.w2i["<PAD>"] for x in temp][:32]
        result.append(temp)

    return result

In [23]:
test = process(testset)

In [24]:
model.eval()

Model(
  (embedding): Embedding(5470, 64)
  (lstm): LSTM(64, 256, num_layers=4, batch_first=True, dropout=0.5, bidirectional=True)
  (linear): Linear(in_features=16384, out_features=12, bias=True)
  (classifier): AttentionClassifier(
    (attention): Attention(
      (linear1): Linear(in_features=256, out_features=24, bias=True)
      (linear2): Linear(in_features=24, out_features=1, bias=True)
      (relu): ReLU(inplace=True)
    )
    (linear): Linear(in_features=256, out_features=12, bias=True)
  )
)

In [25]:
result = model(torch.tensor(test).to(device))
print(result)

tensor([[-2.7656e-05, -2.2271e+01, -2.1413e+01, -2.1863e+01, -1.0559e+01,
         -1.7787e+01, -2.4455e+01, -1.6618e+01, -1.3482e+01, -2.5198e+01,
         -1.5914e+01, -2.0373e+01],
        [-1.3959e+01, -6.1976e-02, -5.2192e+00, -3.5737e+00, -1.2092e+01,
         -4.1886e+00, -4.6672e+00, -1.2275e+01, -9.9678e+00, -6.5426e+00,
         -1.1054e+01, -7.5077e+00],
        [-1.5109e+01, -1.4354e+01, -3.2989e+00, -1.4830e+01, -1.6827e+01,
         -1.3161e+01, -6.7574e+00, -1.5112e+01, -4.0288e-02, -1.9216e+01,
         -6.6045e+00, -1.0004e+01],
        [-1.2627e+01, -8.9444e-01, -5.7307e+00, -6.2980e-01, -1.2105e+01,
         -7.2610e+00, -3.0345e+00, -9.2380e+00, -7.6899e+00, -5.1643e+00,
         -1.0675e+01, -9.0409e+00],
        [-4.2704e+00, -1.8180e+01, -1.0015e+01, -9.5704e+00, -3.8215e-01,
         -1.1348e+01, -1.6217e+01, -1.2162e+00, -5.4185e+00, -2.0195e+01,
         -1.3109e+01, -5.9100e+00],
        [-1.6070e+01, -6.8883e-03, -1.9752e+01, -1.5954e+01, -2.4289e+01,
      

In [26]:
result = result.tolist()

In [27]:
# Normolization
results = []

for i in range(len(result)):
    temp = result[i]
    temp = [x - min(temp) for x in temp]
    temp = [x / max(temp) for x in temp]
    temp = [round(x, 3) for x in temp]

    results.append(temp)

In [28]:
count = 0

for i, r in enumerate(results):
    t = classes[int(torch.argmax(torch.tensor(r)))]
    if t == answare[i]:
        count += 1
        print(t + "✅")
    else:
        print(t + " <- " + answare[i])

print(f"Correct: {count} ({(count / len(answare)) * 100 :.2f}%)")

牡羊✅
金牛✅
射手 <- 雙子
巨蠍✅
獅子✅
金牛 <- 處女
天秤✅
天蠍✅
射手✅
牡羊 <- 魔羯
水瓶✅
水瓶 <- 雙魚
牡羊✅
魔羯 <- 金牛
雙子✅
金牛 <- 巨蠍
獅子✅
金牛 <- 處女
天秤✅
射手 <- 天蠍
射手✅
牡羊 <- 魔羯
水瓶✅
水瓶 <- 雙魚
牡羊✅
金牛✅
雙子✅
巨蠍✅
牡羊 <- 獅子
處女✅
天秤✅
巨蠍 <- 天蠍
射手✅
獅子 <- 魔羯
水瓶✅
天蠍 <- 雙魚
Correct: 22 (61.11%)


In [29]:
import matplotlib.pyplot as plt
import numpy as np

In [30]:
# angles_A = np.linspace(start=0, stop=2*np.pi, num=len(result)+1, endpoint=True)
# values_A = np.concatenate((result, [result[0]]))

# fig, ax = plt.subplots(1, 1, figsize=(5, 5), subplot_kw={'projection': 'polar'})
# ax.plot(angles_A, values_A, 'o-', color="blue", label="A")

# ax.fill(angles_A, values_A, alpha=0.3, color="blue")
# ax.set_thetagrids(angles_A[:-1] * 180 / np.pi, range(12), fontsize=15)
# ax.set_theta_zero_location('N')

In [31]:
# Please check the virtual input of the ONNX model.
torch.onnx.export(model, torch.tensor([test[0]]).to(device=device), 'constellator.onnx')

c:\Users\User\anaconda3\envs\pytorch\lib\site-packages\torch\onnx\symbolic_opset9.py:4315: UserWarning: Exporting a model to ONNX with a batch_size other than 1, with a variable length with LSTM can cause an error when running the ONNX model with a different batch size. Make sure to save the model with a batch size of 1, or define the initial states (h0/c0) as inputs of the model. 
  warnings.warn(
c:\Users\User\anaconda3\envs\pytorch\lib\site-packages\torch\onnx\_internal\jit_utils.py:258: UserWarning: The shape inference of prim::Constant type is missing, so it may result in wrong shape inference for the exported graph. Please consider adding it in symbolic function. (Triggered internally at C:\cb\pytorch_1000000000000\work\torch\csrc\jit\passes\onnx\shape_type_inference.cpp:1888.)
  _C._jit_pass_onnx_node_shape_type_inference(node, params_dict, opset_version)
c:\Users\User\anaconda3\envs\pytorch\lib\site-packages\torch\onnx\utils.py:687: UserWarning: The shape inference of prim::Con

In [32]:
import onnx
import onnx.helper

onnx_model = onnx.load('./constellator.onnx')
print(onnx.helper.printable_graph(onnx_model.graph))

graph torch_jit (
  %input.1[INT64, 1x32]
) initializers (
  %embedding.weight[FLOAT, 5470x64]
  %classifier.attention.linear1.weight[FLOAT, 24x256]
  %classifier.attention.linear1.bias[FLOAT, 24]
  %classifier.attention.linear2.weight[FLOAT, 1x24]
  %classifier.attention.linear2.bias[FLOAT, 1]
  %classifier.linear.weight[FLOAT, 12x256]
  %classifier.linear.bias[FLOAT, 12]
  %onnx::LSTM_742[FLOAT, 2x2048]
  %onnx::LSTM_743[FLOAT, 2x1024x64]
  %onnx::LSTM_744[FLOAT, 2x1024x256]
  %onnx::LSTM_789[FLOAT, 2x2048]
  %onnx::LSTM_790[FLOAT, 2x1024x512]
  %onnx::LSTM_791[FLOAT, 2x1024x256]
  %onnx::LSTM_836[FLOAT, 2x2048]
  %onnx::LSTM_837[FLOAT, 2x1024x512]
  %onnx::LSTM_838[FLOAT, 2x1024x256]
  %onnx::LSTM_883[FLOAT, 2x2048]
  %onnx::LSTM_884[FLOAT, 2x1024x512]
  %onnx::LSTM_885[FLOAT, 2x1024x256]
) {
  %/embedding/Gather_output_0 = Gather(%embedding.weight, %input.1)
  %/lstm/Transpose_output_0 = Transpose[perm = [1, 0, 2]](%/embedding/Gather_output_0)
  %/lstm/Constant_output_0 = Constant[